---
driver:
  name: dokken
  chef_version: 13.2.20
  privileged: true

provisioner:
  name: dokken

transport:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: debian-9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd
    run_list:
      - recipe[apt]

  - name: ubuntu-16
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[simple-mailcatcher]
    attributes:
