name             'simple-mailcatcher'
maintainer       'Yauhen Artsiukhou'
maintainer_email 'jsirex@gmail.com'
license          'apache 2'
description      'Installs mailcatcher using embedded ruby in chef'
long_description 'Installs mailcatcher using embedded ruby in chef'
issues_url       'https://github.com/jsirex/simple-mailcatcher-cookbook/issues'
source_url       'https://github.com/jsirex/simple-mailcatcher-cookbook'
version          '0.1.0'
